export enum IconType {
  ARROW_RIGHT = 'ARROW_RIGHT',
  ARROW_TOP_RIGHT_ON_SQUARE = 'ARROW_TOP_RIGHT_ON_SQUARE',
  CHECK = 'CHECK',
  CHECK_CIRCLE = 'CHECK_CIRCLE',
  MOON = 'MOON',
  PLUS = 'PLUS',
  SUN = 'SUN',
  X_CIRCLE = 'X_CIRCLE',
}
